---
- hosts: webservers
  vars:
    backend_api: "http://192.168.0.3:5000"
  remote_user: root
  tasks:
  - include: tasks/enable_proxy_office.yml
  - include: tasks/basics.yml
  - name: "add repository nginx-release (CentOS6/CentOS7)"
    yum: name="http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm" state=present
  - name: disable the repository (pls set --enablerepo=nginx if you use it)
    replace: dest=/etc/yum.repos.d/nginx.repo regexp="enabled *= *0" replace="enabled=1"
    ignore_errors: True

  - name: install nginx
    yum: name=nginx state=present
  - name: install Nginx Lua Module
    yum: name={{item}} state=present
    with_items:
      - lua
      - lua-devel
  

  - name: Start Nginx
    service: name=nginx enabled=yes state=started